package com.benjamin.factura.ui.theme


import android.app.Activity
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.SideEffect
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalView
import androidx.core.view.WindowCompat

/*
 * Factura — ui/theme/AppTheme.kt
 *
 * Material3 theming. dynamicColor is intentionally NOT an option here — no
 * dynamicLightColorScheme()/dynamicDarkColorScheme() branch for Android 12+.
 * Factura's brand teal (#1D6A72) is the color identity everywhere, on every
 * OS version, full stop.
 *
 * These tonal palettes were hand-built around the #1D6A72 seed rather than
 * generated by Material Theme Builder — treat the container/variant tones as
 * a solid starting point, not pixel-exact HCT output. Swap individual roles
 * freely; primary/onPrimary are the two values that must never change.
 */

private val LightColorScheme = lightColorScheme(
    primary = Color(0xFF1D6A72),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFA6EEF2),
    onPrimaryContainer = Color(0xFF002022),

    secondary = Color(0xFF4A6367),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFCDE7EB),
    onSecondaryContainer = Color(0xFF051F22),

    // Warm amber/gold tertiary — reserved for money-forward accents (paid
    // badges, positive revenue deltas), distinct from the teal brand primary.
    tertiary = Color(0xFF8C5000),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDDB3),
    onTertiaryContainer = Color(0xFF2C1600),

    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),

    background = Color(0xFFFAFDFC),
    onBackground = Color(0xFF191C1C),
    surface = Color(0xFFFAFDFC),
    onSurface = Color(0xFF191C1C),
    surfaceVariant = Color(0xFFDAE4E4),
    onSurfaceVariant = Color(0xFF3F4949),

    outline = Color(0xFF6F7979),
    outlineVariant = Color(0xFFBEC8C8),
    scrim = Color(0xFF000000),

    inverseSurface = Color(0xFF2D3131),
    inverseOnSurface = Color(0xFFEFF1F0),
    inversePrimary = Color(0xFF83D2D9),

    surfaceDim = Color(0xFFD9DBDA),
    surfaceBright = Color(0xFFF9FDFC),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF3F5F4),
    surfaceContainer = Color(0xFFEDEFEE),
    surfaceContainerHigh = Color(0xFFE7EAE9),
    surfaceContainerHighest = Color(0xFFE2E4E3)
)

private val DarkColorScheme = darkColorScheme(
    primary = Color(0xFF83D2D9),
    onPrimary = Color(0xFF00373C),
    primaryContainer = Color(0xFF014F55),
    onPrimaryContainer = Color(0xFFA6EEF2),

    secondary = Color(0xFFB1CBCF),
    onSecondary = Color(0xFF1B3437),
    secondaryContainer = Color(0xFF324B4E),
    onSecondaryContainer = Color(0xFFCDE7EB),

    tertiary = Color(0xFFFFB945),
    onTertiary = Color(0xFF492900),
    tertiaryContainer = Color(0xFF693C00),
    onTertiaryContainer = Color(0xFFFFDDB3),

    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),

    background = Color(0xFF191C1C),
    onBackground = Color(0xFFE0E3E2),
    surface = Color(0xFF191C1C),
    onSurface = Color(0xFFE0E3E2),
    surfaceVariant = Color(0xFF3F4949),
    onSurfaceVariant = Color(0xFFBEC8C8),

    outline = Color(0xFF899393),
    outlineVariant = Color(0xFF3F4949),
    scrim = Color(0xFF000000),

    inverseSurface = Color(0xFFE0E3E2),
    inverseOnSurface = Color(0xFF191C1C),
    inversePrimary = Color(0xFF1D6A72),

    surfaceDim = Color(0xFF191C1C),
    surfaceBright = Color(0xFF3F4342),
    surfaceContainerLowest = Color(0xFF131615),
    surfaceContainerLow = Color(0xFF191C1C),
    surfaceContainer = Color(0xFF1D2020),
    surfaceContainerHigh = Color(0xFF282B2A),
    surfaceContainerHighest = Color(0xFF333635)
)

/**
 * Root Factura theme. Wrap MainActivity's setContent { } (and any Compose
 * previews) in this — never call MaterialTheme directly.
 *
 * @param darkTheme follows the system setting by default; pass an explicit
 *   value if Settings ever grows a manual light/dark toggle.
 */
@Composable
fun FacturaTheme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    content: @Composable () -> Unit
) {
    val colorScheme = if (darkTheme) DarkColorScheme else LightColorScheme

    val view = LocalView.current
    if (!view.isInEditMode) {
        SideEffect {
            val window = (view.context as Activity).window
            val insetsController = WindowCompat.getInsetsController(window, view)
            // Status/nav bar backgrounds are handled by edge-to-edge on API 35+;
            // this only controls icon contrast (light icons on dark content, etc.).
            insetsController.isAppearanceLightStatusBars = !darkTheme
            insetsController.isAppearanceLightNavigationBars = !darkTheme
        }
    }

    MaterialTheme(
        colorScheme = colorScheme,
        typography = Typography,
        content = content
    )
}